name: CI/CD Frontend -> Docker Hub -> EC2

on:
  push:
    branches: [deploy]
  workflow_dispatch:

jobs:
  build-push-deploy:
    runs-on: [self-hosted, front]
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build imagen frontend
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/front-eval2:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/front-eval2:${{ github.sha }} \
            .

      - name: Push a Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/front-eval2:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/front-eval2:${{ github.sha }}

      - name: Deploy local (runner == EC2-front)
        run: |
          cp docker-compose.yml ~/app/docker-compose.yml
          cd ~/app
          docker compose pull
          docker compose up -d
          docker image prune -f
          docker ps
